services:
  guko-bot:
    image: ghcr.io/shuijiao1/guko:latest
    container_name: guko-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./servers.json:/data/servers.json
      - ./keys:/data/keys
      - ./media:/data/media
      - ./tmp:/data/tmp
